# fly.toml app configuration file generated for miodatabase on 2025-03-30T00:16:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "miodatabase"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  worker = "python bot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


